version: '3.8'
services:
  backend:
    container_name: veri-backend
    restart: always
    build: veri-backend/
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  frontend:
    container_name: veri-frontend
    restart: always
    build: veri-frontend/
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - backend
