name: Deploy on dev server
on:
  push:
    branches:
      - develop
jobs:
  build:
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      SSH_KEY_PATH: ~/.ssh/private.key
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > $SSH_KEY_PATH
          sudo chmod 600 $SSH_KEY_PATH
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: Remove old codes
        run: ssh -i $SSH_KEY_PATH github-user@getveri.xyz "rm -fr /home/github-user/dev/veri/veri-*"
      - name: Copy new codes
        run: |
          tar czf - veri-*end | \
          ssh -i $SSH_KEY_PATH github-user@getveri.xyz "cd /home/github-user/dev/veri/ && tar xvzf -"
      - name: run update script
        run: ssh -i $SSH_KEY_PATH github-user@getveri.xyz "sudo ./automation.sh dev"